# Generated by Django 5.0.1 on 2024-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Concluido')]),
        ),
    ]
